# Generated by Django 5.1 on 2024-09-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customer_order_oredrproduct_shippingaddress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OredrProduct',
            new_name='OrderProduct',
        ),
    ]
