# Generated by Django 5.1.1 on 2024-09-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_rename_oredrproduct_orderproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
